blog/urls.py
from django.urls import path
from blog.views import blog_login_view, blog_logout_view, blog_register_view, BlogHomeView, BlogDetailView, BlogCommentView, BlogCreateView, BlogDeleteView, BlogUpdateView

app_name = 'blog'
urlpatterns = [

    path('<slug>/update_post/', BlogUpdateView.as_view(), name='blog_post_update_url'),
    path('<slug>/delete_post/', BlogDeleteView.as_view(), name='blog_post_delete_url'),
    path('create_post/', BlogCreateView.as_view(), name='blog_post_create_url'),
    path('accounts/logout/', blog_logout_view, name='blog_logout_url'),
    path('accounts/login/', blog_login_view, name='blog_login_url'),
    path('login/', blog_login_view, name='blog_login_url'),
    path('register/', blog_register_view, name='blog_register_url'),
    path('', BlogHomeView.as_view(), name='blog_home_url'),
    path('<slug>/comment/', BlogCommentView.as_view(), name='add_comment_url'),
    path('<slug>/', BlogDetailView.as_view(), name = 'post_detail_url'),
]

sumahwrites/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse('post_detail', args=[str(self.id)])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' %(self.post.title, self.name)

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Post, Comment

class NewUserForm(UserCreationForm):
    username        = forms.CharField( 
                        widget=forms.TextInput(
                            attrs={
                                'class': 'form-control',
                                'placeholder':'username',
                                }
                            )
                        )
    email        = forms.EmailField( 
                        widget=forms.TextInput(
                            attrs={
                                'class': 'form-control',
                                'placeholder':'email',
                                }
                            )
                        )
                    
    password1        = forms.CharField(
                        widget=forms.PasswordInput(
                            attrs={
                                'class': 'form-control',
                                'placeholder':'password',
                                }
                            )
                        )
    password2        = forms.CharField(
                        widget=forms.PasswordInput(
                            attrs={
                                'class': 'form-control',
                                'placeholder':'confirm password',
                                }
                            )
                        )
    class Meta:
        model = User
        fields = [
            'username', 
            'email', 
            'password1', 
            'password2'
            ]


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','rows': 20}),
            'body': forms.Textarea(
                attrs={
                    'row':50,
                    'label': "Comment",
                    }
                    ),
        }


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'author', 'body')

        widgets ={
            'title':forms.TextInput(attrs={'class':'create-post-title'}),
            # 'author':forms.TextInput(attrs={'class':'form-control'}),
            'body':forms.Textarea(attrs={'class':'create-post-body'}),
        }

blog/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm, AddCommentForm, CreatePostForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView

from .models import Post, Comment

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


# Create your views here.

class BlogUpdateView(PermissionRequiredMixin, UpdateView):
    # permission 
    permission_required = 'blog.change_post'

    model = Post
    template_name = 'blog_post_update.html'
    fields = ['title', 'body']
    success_url = '/'
    


class BlogDeleteView(PermissionRequiredMixin, DeleteView):
    # permission 
    permission_required = 'blog.delete_post'

    model = Post
    template_name = 'blog_post_delete.html'
    context_object_name = 'post'
    success_url = '/'


class BlogCreateView(PermissionRequiredMixin, CreateView):
    # permission 
    permission_required = 'blog.add_post'

    model = Post
    form_class = CreatePostForm
    template_name = 'blog_post_creation.html'
    success_url = '/'
    



class BlogCommentView(LoginRequiredMixin, CreateView):
    # login_url = 'login/'
    # redirect_field_name = 'next'
    model = Comment
    form_class = AddCommentForm
    template_name ='blog_post_comment.html' 
    success_url = '/' 

    def form_valid(self, form):
        post = Post.objects.get(slug=self.kwargs['slug'])
        form.instance.post_id = post.id
        return super(BlogCommentView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = Post.objects.get(slug=self.kwargs['slug'])
        return context



class BlogDetailView(DetailView):
    model = Post
    template_name = "blog_post_detail.html"
    context_object_name = 'post'

class BlogHomeView(ListView):
    model = Post
    template_name = "home.html"
    context_object_name = 'posts'


def blog_register_view(request):
    form = NewUserForm()

    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been created')
            return redirect('blog:blog_login_url')
        else:
            messages.info(
                request, 
                "Something is Wrong: \n\n email must be in this format 'xyz@email.com' \n password- 8 digits, Contain Cap Letter and a Number"
                )
        

    context = {'form': form}
    return render(request, 'blog_register.html', context)


def blog_login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('blog:blog_home_url')
        else:
            messages.info(request, 'Username or Password is incorrect ')

    context = {}
    return render(request, 'blog_login.html', context)

def blog_logout_view(request):
    logout(request)
    return redirect('blog:blog_home_url')

sumahwrites/blog/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm, AddCommentForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView

from .models import Post, Comment


# Create your views here.

class BlogCommentView(CreateView):
    model = Comment
    form_class = AddCommentForm
    template_name ='blog_post_comment.html' 
    success_url = '/' 

    def form_valid(self, form):
        form.instance.post__slug = self.kwargs['slug']
        return super().form_valid(form)

    # def form_valid(self, form):
    #     return super(BlogCommentView, self).form_valid(form)

    # def form_invalid(self, form):
    #     post = Post.objects.get(slug=current_slug)
    #     form.instance.post_id = post   
    #     return super().form_invalid(form)

    # def get_initial(self, *args, **kwargs):
    #     initial = super().get_initial(**kwargs)
    #     initial['body'] = 'Enter your comment here'
    #     return initial


class BlogDetailView(DetailView):
    model = Post
    template_name = "blog_post_detail.html"
    context_object_name = 'post'

class BlogHomeView(ListView):
    model = Post
    template_name = "home.html"
    context_object_name = 'posts'


def blog_register_view(request):
    # if request.user.is_authenticated:
    #     return redirect('home')
    # else:
    form = NewUserForm()

    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been created')
            return redirect('blog:blog_login_url')
        else:
            messages.info(
                request, 
                "Something is Wrong: \n\n email must be in this format 'xyz@email.com' \n password- 8 digits, Contain Cap Letter and a Number"
                )
        

    context = {'form': form}
    return render(request, 'blog_register.html', context)


def blog_login_view(request):
    # if request.user.is_authenticated:
    #     return redirect('home')
    # else:
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('blog:blog_home_url')
        else:
            messages.info(request, 'Username or Password is incorrect ')

    context = {}
    return render(request, 'blog_login.html', context)

blog/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sumahwrites</title>

    <style>
        html {
            height: auto;
        }
        body {
            height: 100%;
            margin: 0;
            background-repeat: no-repeat;
            background-attachment: fixed;
            margin: 30px;
        }

        a{
            text-decoration: none;
        }

        .nav-left{
            font-size: 3rem;
        }
        .main-bg {
        background: #424242;
        background: linear-gradient( #424242, #212121);
        }

        /* Text Color */
        .text-whitesmoke {
            color: whitesmoke
        }
        .text-darkyellow {
            color: rgba(255, 235, 59, 0.432)
        }

        .single-post{
            max-width: 50%;
            min-width: 400px;
            margin-bottom: 30px;
        }

        .single-post-body{
            height: 50px;
            overflow:hidden;
        }

        .single-post-author{
            color: blanchedalmond;
        }


        /* comment section style */
        hr{
            border: 2px solid white;
        }

        .comments{
            max-width: 50%;
            min-width: 400px;
            
        }
        .comments h2{
            color: rgba(255, 235, 59, 0.432);
            font-size: 2rem;

        }

        .single-comment{
            padding-bottom: 5px;
        }
        .single-comment-body{
            color: white;
            padding-left: 10px;
        }
        .single-comment-name{
            color: rgba(219, 202, 44, 0.432);
        }

        .form-button {
            background-color: rgba(255, 235, 59, 0.24);
            border-color: rgba(255, 235, 59, 0.24);
            color: #e6e6e6;
            height: 40px;
        }
        .form-button:hover,
        .form-button:focus,
        .form-button:active,
        .form-button.active,
        .form-button:active:focus,
        .form-button:active:hover,
        .form-button.active:hover,
        .form-button.active:focus {
            background-color: rgba(255, 235, 59, 0.473);
            border-color: rgba(255, 235, 59, 0.473);
            color: #e6e6e6;
        }

        .form-control:focus,
        .border-line:focus {
                border-color: #FFEB3B;
                background-color: #616161;
                color: #e6e6e6;
            }
            .form-control,
            .form-control:focus {
                box-shadow: none;
            }
            .form-control::-webkit-input-placeholder { color: #BDBDBD; }

            .add-comment{
                color: white;
            }

            #create-post-button{
                color: white;

            }
    </style>
</head>
    <body class="main-bg">
        <nav style="position: relative;">
            <a href="{% url 'blog:blog_home_url' %}">
                <nav-left class="text-whitesmoke nav-left">Sumah's blog</nav-left>
            </a>

            <span style="position: absolute; right: 10px; color: white;">
                
                {% if not request.user.is_authenticated %}
                <a href="{% url 'blog:blog_login_url' %}" style="color: yellow;">LOGIN </a>
                to be able to comment on a Post 
                {% endif %}                    
                  
                
                {% if request.user.is_authenticated %}
                    <span> <a href="{% url 'blog:blog_logout_url' %}" style="color: red; padding-left: 20px;">LOGOUT</a></span>
                {% endif %}
                    
                
            </span>
            
        </nav>

        <section class="blog-body">
            
            {% block content %}
                
            {% endblock content %}
                
                
        </section>
    </body>
</html>

blog/templates/blog_login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sumah's Blog</title>

    <style>
        html {
    height: 100%;
}
body {
    height: 100%;
    margin: 0;
    background-repeat: no-repeat;
    background-attachment: fixed;
}

/* Text Align */
.text-c {
    text-align: center;
}
.text-l {
    text-align: left;
}
.text-r {
    text-align: right
}
.text-j {
    text-align: justify;
}

/* Text Color */
.text-whitesmoke {
    color: whitesmoke
}
.text-darkyellow {
    color: rgba(255, 235, 59, 0.432)
}

/* Lines */

.line-b {
    border-bottom: 1px solid #FFEB3B !important;
}

/* Buttons */
.button {
    border-radius: 3px;
}
.form-button {
    background-color: rgba(255, 235, 59, 0.24);
    border-color: rgba(255, 235, 59, 0.24);
    color: #e6e6e6;
    height: 40px;
}
.form-button:hover,
.form-button:focus,
.form-button:active,
.form-button.active,
.form-button:active:focus,
.form-button:active:hover,
.form-button.active:hover,
.form-button.active:focus {
    background-color: rgba(255, 235, 59, 0.473);
    border-color: rgba(255, 235, 59, 0.473);
    color: #e6e6e6;
}
.button-l {
    width: 100% !important;
}

/* Margins g(global) - l(left) - r(right) - t(top) - b(bottom) */

.margin-g {
    margin: 15px;
}
.margin-g-sm {
    margin: 10px;
}
.margin-g-md {
    margin: 20px;
}
.margin-g-lg {
    margin: 30px;
}

.margin-l {
    margin-left: 15px;
}
.margin-l-sm {
    margin-left: 10px;
}
.margin-l-md {
    margin-left: 20px;
}
.margin-l-lg {
    margin-left: 30px;
}

.margin-r {
    margin-right: 15px;
}
.margin-r-sm {
    margin-right: 10px;
}
.margin-r-md {
    margin-right: 20px;
}
.margin-r-lg {
    margin-right: 30px;
}

.margin-t {
    margin-top: 15px;
}
.margin-t-sm {
    margin-top: 10px;
}
.margin-t-md {
    margin-top: 20px;
}
.margin-t-lg {
    margin-top: 30px;
}

.margin-b {
    margin-bottom: 15px;
}
.margin-b-sm {
    margin-bottom: 10px;
}
.margin-b-md {
    margin-bottom: 20px;
}
.margin-b-lg {
    margin-bottom: 30px;
}

/* Bootstrap Form Control Extension */

.form-control,
.border-line {
    background-color: #5f5f5f;
    background-image: none;
    border: 1px solid #424242;
    border-radius: 1px;
    color: inherit;
    display: block;
    padding: 6px 12px;
    transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
    width: 100%;
    height: 50px;
    margin-bottom: 10px;
}
.form-control:focus,
.border-line:focus {
    border-color: #FFEB3B;
    background-color: #616161;
    color: #e6e6e6;
}
.form-control,
.form-control:focus {
    box-shadow: none;
}
.form-control::-webkit-input-placeholder { color: #BDBDBD; }

/* Container */

.container-content {
    background-color: #3a3a3aa2;
    color: inherit;
    padding: 15px 20px 20px 20px;
    border-color: #FFEB3B;
    border-image: none;
    border-style: solid solid none;
    border-width: 1px 0;
}

/* Backgrounds */

.main-bg {

    background: #424242;
    background: linear-gradient( #424242, #212121);
}

/* Login & Register Pages*/

.login-container {
    max-width: 400px;
    z-index: 100;
    margin: 0 auto;
    padding-top: 100px;
}
.login.login-container {
    width: 300px;
}
.wrapper.login-container {
    margin-top: 140px;
}
.logo-badge {
    color: #e6e6e6;
    font-size: 80px;
    font-weight: 800;
    letter-spacing: -10px;
    margin-bottom: 0;
}
    </style>
</head>
<body class="main-bg">
    <div class="login-container text-c animated flipInX">
            <div>
                <h1 class="logo-badge text-whitesmoke"><span class="fa fa-user-circle"></span></h1>
            </div>
                <h3 class="text-whitesmoke">
                    <a href="{% url 'blog:blog_home_url' %}" style="text-decoration: none; color: white;">Sumah's Blog - <span style="color: yellow;">Click here to continue reading</span> </a>
                </h3>
                <p class="text-whitesmoke">Sign In</p>
            <div class="container-content">
                <form class="margin-t" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input name="username" type="text" class="form-control" placeholder="Username" required="">
                    </div>
                    <div class="form-group">
                        <input name="password" type="password" class="form-control" placeholder="*****" required="">
                    </div>
                    <input type="submit" class="form-button button-l margin-b" placeholder="Sign In">
    
                    <a class="text-darkyellow" href="#"><small>Forgot your password?</small></a>
                    <p class="text-whitesmoke text-center"><small>Do not have an account?</small></p>
                    <a class="text-darkyellow" href="{% url 'blog:blog_register_url' %}"><small>Sign Up</small></a>
                </form>
                <p class="margin-t text-whitesmoke"><small> Daniel Sumah &copy; 2021</small> </p>
            </div>
            {% for message in messages %}
				<p id="messages">{{message}}</p>
			{% endfor %}
        </div>
</body>
</html>

blog/templates/blog_post_comment.html
{% extends 'base.html' %}




{% block content %}
    <form method="POST" class="add-comment">
        {% csrf_token %}
        {{ form.as_p}}
        <input class="form-button button-l margin-b" type="submit" value="Submit Comment">
    </form>
{% endblock content %}
    

blog/templates/blog_post_creation.html
{% extends 'base.html' %}

<style>
    input#id_title, #id_author{
        min-width: 300px;
        max-width: 600px;
        height: 50px;
    }

    #id_body{
        min-width: 300px;
        max-width: 600px;
        height: 100px;
    }
</style>

{% block content %}
    <form method="POST" class="add-comment">
        {% csrf_token %}
        {{ form.as_p}}
        <input class="form-button button-l margin-b" type="submit" value="Create Post">
    </form>
{% endblock content %}
    

blog/templates/blog_post_delete.html
{% extends 'base.html' %}


{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h2 style="color: white;">Are you sure you want to delete this post? <span>" {{ post.title }} "</span></h2>
        
        <input type="submit" value="Delete" style="color: white; background-color: red;">
    </form>
{% endblock content %}
    

blog/templates/blog_post_detail.html
{% extends 'base.html' %}


{% block content %}
    <div class="single-post">
        <h1 class="single-post-header text-darkyellow">{{post.title}} - {{ post.date_added }}</h1>
        <p  class="single-post-body text-whitesmoke" style="height: auto;">{{post.body}}</p>
        <p class="single-post-author">written by: {{post.author}}</p>
    </div>

    
    {% if request.user.is_authenticated %}
        
        {% if request.user.name == 'admin' %}
            <span>
                <a href="{% url 'blog:blog_post_update_url' slug=post.slug %}" style="color: Orange; margin-right: 40px;">Update Post</a>
                <a href="{% url 'blog:blog_post_delete_url' slug=post.slug %}" style="color: red;">Delete Post</a>
            </span>
        {% endif %}
            
    {% endif %}
    
    <hr>

    <div class="comments">
        <h2>Comments....</h2> 
        
    
        <a href="{% url 'blog:add_comment_url' slug=post.slug %}" style="color: yellow;">Add Comment</a>

        
        {% if not post.comments.all %}
            No Comments on this post, be the first to <a href="{% url 'blog:add_comment_url' slug=post.slug %}">Add one</a>
        {% else %}
            {% for comment in post.comments.all reversed %}
                <div class="single-comment">
                    <strong><p class="single-comment-name">{{comment.name}} - {{ comment.date_added}}</p></strong>
                    <p class="single-comment-body">{{comment.body}}</p>
                    
                </div>
                
            {% endfor %}            
        {% endif %}
            
    </div>

        
{% endblock content %}
    

blog/templates/blog_post_update.html
{% extends 'base.html' %}



{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Update Post </button>
    </form>
{% endblock content %}
    

blog/templates/blog_register.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sumah's Blog</title>

    <style>
        html {
    height: 100%;
}
body {
    height: 100%;
    margin: 0;
    background-repeat: no-repeat;
    background-attachment: fixed;
}

/* Text Align */
.text-c {
    text-align: center;
}
.text-l {
    text-align: left;
}
.text-r {
    text-align: right
}
.text-j {
    text-align: justify;
}

/* Text Color */
.text-whitesmoke {
    color: whitesmoke
}
.text-darkyellow {
    color: rgba(255, 235, 59, 0.432)
}

/* Lines */

.line-b {
    border-bottom: 1px solid #FFEB3B !important;
}

/* Buttons */
.button {
    border-radius: 3px;
}
.form-button {
    background-color: rgba(255, 235, 59, 0.24);
    border-color: rgba(255, 235, 59, 0.24);
    color: #e6e6e6;
    height: 40px;
}
.form-button:hover,
.form-button:focus,
.form-button:active,
.form-button.active,
.form-button:active:focus,
.form-button:active:hover,
.form-button.active:hover,
.form-button.active:focus {
    background-color: rgba(255, 235, 59, 0.473);
    border-color: rgba(255, 235, 59, 0.473);
    color: #e6e6e6;
}
.button-l {
    width: 100% !important;
}

/* Margins g(global) - l(left) - r(right) - t(top) - b(bottom) */

.margin-g {
    margin: 15px;
}
.margin-g-sm {
    margin: 10px;
}
.margin-g-md {
    margin: 20px;
}
.margin-g-lg {
    margin: 30px;
}

.margin-l {
    margin-left: 15px;
}
.margin-l-sm {
    margin-left: 10px;
}
.margin-l-md {
    margin-left: 20px;
}
.margin-l-lg {
    margin-left: 30px;
}

.margin-r {
    margin-right: 15px;
}
.margin-r-sm {
    margin-right: 10px;
}
.margin-r-md {
    margin-right: 20px;
}
.margin-r-lg {
    margin-right: 30px;
}

.margin-t {
    margin-top: 15px;
}
.margin-t-sm {
    margin-top: 10px;
}
.margin-t-md {
    margin-top: 20px;
}
.margin-t-lg {
    margin-top: 30px;
}

.margin-b {
    margin-bottom: 15px;
}
.margin-b-sm {
    margin-bottom: 10px;
}
.margin-b-md {
    margin-bottom: 20px;
}
.margin-b-lg {
    margin-bottom: 30px;
}

/* Bootstrap Form Control Extension */

.form-control,
.border-line {
    background-color: #5f5f5f;
    background-image: none;
    border: 1px solid #424242;
    border-radius: 1px;
    color: inherit;
    display: block;
    padding: 6px 12px;
    transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
    width: 100%;
    height: 50px;
    margin-bottom: 10px;
}
.form-control:focus,
.border-line:focus {
    border-color: #FFEB3B;
    background-color: #616161;
    color: #e6e6e6;
}
.form-control,
.form-control:focus {
    box-shadow: none;
}
.form-control::-webkit-input-placeholder { color: #BDBDBD; }

/* Container */

.container-content {
    background-color: #3a3a3aa2;
    color: inherit;
    padding: 15px 20px 20px 20px;
    border-color: #FFEB3B;
    border-image: none;
    border-style: solid solid none;
    border-width: 1px 0;
}

/* Backgrounds */

.main-bg {

    background: #424242;
    background: linear-gradient( #424242, #212121);
}

/* Login & Register Pages*/

.login-container {
    max-width: 400px;
    z-index: 100;
    margin: 0 auto;
    padding-top: 100px;
}
.login.login-container {
    width: 300px;
}
.wrapper.login-container {
    margin-top: 140px;
}
.logo-badge {
    color: #e6e6e6;
    font-size: 80px;
    font-weight: 800;
    letter-spacing: -10px;
    margin-bottom: 0;
}
    </style>
</head>
<body class="main-bg">
    <div class="login-container text-c animated flipInX">
            <div>
                <h1 class="logo-badge text-whitesmoke"><span class="fa fa-user-circle"></span></h1>
            </div>
                <h3 class="text-whitesmoke"><a href="{% url 'blog:blog_home_url' %}" style="text-decoration: none; color: white;">Sumah's Blog - Home</a></h3>
                <div>
                    {% for message in messages %}
				        <p id="messages" style="color: white; background-color: black;">{{message}}</p>
			        {% endfor %}
                </div>
                <p class="text-whitesmoke">Sign Up</p>
            <div class="container-content">
                <form class="margin-t" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <!-- <input type="text" class="form-control" placeholder="Username" required=""> -->
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <!-- <input type="email" class="form-control" placeholder="email" required=""> -->
                        {{ form.email }}
                    </div>
                    <div class="form-group">
                        <!-- <input type="password" class="form-control" placeholder="password" required=""> -->
                        {{ form.password1 }}
                    </div>
                    <div class="form-group">
                        <!-- <input type="password" class="form-control" placeholder="confirm password" required=""> -->
                        {{ form.password2 }}

                    </div>
                    <input type="submit" class="form-button button-l margin-b" value="Sign Up">
    
                    <p class="text-whitesmoke text-center"><small>Already have an account?</small></p>
                    <a class="text-darkyellow" href="{% url 'blog:blog_login_url' %}"><small>Sign In</small></a>
                </form>
                <p class="margin-t text-whitesmoke"><small> Your Name &copy; 2021</small> </p>
            </div>
        </div>
</body>
</html>

blog/templates/home.html
{% extends 'base.html' %}


{% block content %}

    {% if request.user.is_authenticated %}
            
        {% if request.user.name == 'admin' %}
            <h4>
                <a href="{% url 'blog:blog_post_create_url' %}" style="text-decoration: none; color: white; background-color: blue; padding: 5px; border-radius: 1px;">
                    Create New Post
                </a>
            </h4>
        {% endif %}
        
    {% endif %}

    
    {% for post in posts reversed %}
    <a href="{% url 'blog:post_detail_url' slug=post.slug %}">
        <div class="single-post">
            <h1 class="single-post-header text-darkyellow">{{post.title}} - {{ post.date_added }}</h1>
            <p  class="single-post-body text-whitesmoke">{{post.body}}</p>
            <p class="single-post-author">written by: {{post.author}}</p>
        </div>
    </a>    
    <hr style="color: white;">
    {% endfor %}
{% endblock content %}
    